server.port: ${PORT:0}

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core: DEBUG

spring:
  data:
    mongodb:
      database: recommendation-db
      host: localhost
      port: 27017
      auto-index-creation: true
  application:
    name: recommendation