server.port: ${PORT:0}

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    '[org.hibernate.sql]': DEBUG
    '[org.hibernate.type.descriptor.sql]': TRACE

# Strongly recommend to set this property to "none" in a production environment!
spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: password
    hikari:
      initialization-fail-timeout: 60000
  application:
    name: review
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true