version: '2.1'

services:
  product:
    build: microservices/product-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eureka:
        condition: service_started
      mongodb:
        condition: service_healthy

  recommendation:
    build: microservices/recommendation-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      eureka:
        condition: service_started

  review:
    build: microservices/review-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eureka:
        condition: service_started

  product-composite:
    build: microservices/product-composite-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - product
      - recommendation
      - review
      - eureka
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:3.6.9
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 10s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:5.7
    restart: always
    mem_limit: 350m
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: review-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      #    healthcheck:
      #      test: ["CMD", "mysqladmin", "ping", "-uuser", "ppwd", "-h", "localhost"]
      #      interval: 1000s
      #      timeout: 5s
      #      retries: 10


  eureka:
    build: spring-cloud/eureka-server
    mem_limit: 350m
    ports:
      - "8761:8761"

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/gateway
    mem_limit: 350m
    depends_on:
      eureka:
        condition: service_started
    ports:
      - "443:8443"

  auth-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/authorization-server
    mem_limit: 350m