app:
  eureka-server: localhost
  eureka-username: user
  eureka-password: password
  auth-server: localhost
  tenant-name: vw-dev.us.auth0.com
server.port: 8443

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

ribbon.ServerListRefreshInterval: 5000

ribbon.NFLoadBalancerPingInterval: 5

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-composite
          uri: lb://product-composite
          predicates:
            - Path=/reactive/product-composite/**
        - id: eureka-api
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/api/{segment}
          filters:
            - SetPath=/eureka/{segment}
        - id: eureka-web-start
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-web-other
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**
        - id: product-actuator
          uri: lb://product/actuator/*
          predicates:
            - Path=/reactive/product/actuator/**
        - id: oauth-server
          uri: lb://auth-server
          predicates:
            - Path=/oauth/**
  security:
    oauth2:
      resourceserver:
        jwt:
#          jwk-set-uri: http://${app.auth-server}:9999/.well-known/jwks.json
          issuer-uri: https://${app.auth-server.tenant-name}/

server:
  ssl:
    key-alias: localhost
    key-store: classpath:keystore/edge.p12
    key-store-password: password
    key-store-type: PKCS12

---

spring.profiles: docker
  
app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation 
    port: 8080
  review-service:
    host: review
    port: 8080
  eureka-server: eureka
  auth-server: auth-server
