server.port: ${PORT:0}
logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core: DEBUG
spring:
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: product-db
  application:
    name: product

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    intialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

app:
  eureka-username: user
  eureka-password: password
  eureka-server: localhost
---

spring.profiles: docker

spring:
  data:
    mongodb:
      host: mongodb

server:
  port: 8080

app:
  eureka-server: eureka